export const category = [
    { id: 1, name: 'truck' },
    { id: 2, name: 'scooter' },
    { id: 3, name: 'crouser' },
    { id: 4, name: 'tractor' },
    { id: 5, name: 'workshop' },
]

export const 
imageList = [
    { id: 1, catId: 1, imgURL: 'https://i.ibb.co/rb24h94/Truck091.jpg'},
    { id: 3, catId: 1, imgURL: "https://i.ibb.co/r0b3yFT/Unbeladen.jpg" },
    { id: 4, catId: 1, imgURL: 'https://i.ibb.co/j8W2Mpx/TRUCK-Elektro-Swissdrive.jpg' },
    { id: 2, catId: 1, imgURL: 'https://i.ibb.co/S78w74c/Truck09-Kopie.jpg' },
    { id: 5, catId: 1, imgURL: 'https://i.ibb.co/r0z7qgx/IMG-1378.jpg' },
    { id: 6, catId: 1, imgURL: 'https://i.ibb.co/r0z7qgx/IMG-1378.jpg' },
    { id: 7, catId: 1, imgURL: 'https://i.ibb.co/j8W2Mpx/TRUCK-Elektro-Swissdrive.jpg' },
    { id: 8, catId: 1, imgURL: 'https://i.ibb.co/nBMzRr4/TRUCK-11-short.jpg' },
    { id: 9, catId: 1, imgURL: 'https://i.ibb.co/tJ8nKqc/IMG-1367-Kopie.jpg' },
    { id: 10, catId: 1, imgURL: 'http://www.mydeen.org/wp-content/uploads/2018/10/Environment-earth_crop.jpg' },
    { id: 11, catId: 2, imgURL: 'https://i.ibb.co/r7rXcSp/girl1.jpg" alt="girl1' },
    { id: 12, catId: 2, imgURL: 'https://i.ibb.co/r7rXcSp/girl1.jpg" alt="girl1fb1.jpg' },
    { id: 13, catId: 2, imgURL: 'https://i.ibb.co/88kNLCG/Blue.png" alt="girl1' },
    { id: 14, catId: 2, imgURL: 'https://i.ibb.co/r7rXcSp/girl1.jpg" alt="girl1' },
    { id: 15, catId: 2, imgURL: 'https://i.ibb.co/88kNLCG/Blue.png' },
    { id: 16, catId: 2, imgURL: 'https://i.ibb.co/r7rXcSp/girl1.jpg" alt="girl1' },
    { id: 17, catId: 2, imgURL: 'https://i.ibb.co/r7rXcSp/girl1.jpg" alt="girl1' },
    { id: 18, catId: 2, imgURL: 'https://i.ibb.co/r7rXcSp/girl1.jpg" alt="girl1' },
    { id: 19, catId: 2, imgURL: 'https://i.ibb.co/88kNLCG/Blue.png' },
    { id: 20, catId: 2, imgURL: 'https://i.ibb.co/88kNLCG/Blue.png' },
    { id: 21, catId: 3, imgURL: 'https://i.ibb.co/sjfZGYZ/IMG-1288.jpg' },
    { id: 22, catId: 3, imgURL: 'https://i.postimg.cc/Gt1QtyFN/photo-grid-600-600-2.jpg' },
    { id: 23, catId: 3, imgURL: 'https://i.ibb.co/sjfZGYZ/IMG-1288.jpg' },
    { id: 24, catId: 3, imgURL: 'https://i.postimg.cc/Gt1QtyFN/photo-grid-600-600-2.jpg' },
    { id: 25, catId: 3, imgURL: 'https://i.ibb.co/Lg6jSdq/IMG-1292.jpg' },
    { id: 26, catId: 3, imgURL: 'https://i.postimg.cc/Gt1QtyFN/photo-grid-600-600-2.jpg' },
    { id: 27, catId: 3, imgURL: 'https://i.ibb.co/Lg6jSdq/IMG-1292.jpg' },
    { id: 28, catId: 3, imgURL: 'https://i.postimg.cc/Gt1QtyFN/photo-grid-600-600-2.jpg' },
    { id: 29, catId: 3, imgURL: 'https://i.postimg.cc/Gt1QtyFN/photo-grid-600-600-2.jpg' },
    { id: 30, catId: 3, imgURL: 'https://i.postimg.cc/Gt1QtyFN/photo-grid-600-600-2.jpg' },
    { id: 31, catId: 4, imgURL: 'https://ibb.co/PW9kzS8' },
    { id: 32, catId: 4, imgURL: 'https://i.postimg.cc/Gt1QtyFN/photo-grid-600-600-2.jpg' },
    { id: 33, catId: 4, imgURL: 'https://i.postimg.cc/Gt1QtyFN/photo-grid-600-600-2.jpg' },
    { id: 34, catId: 4, imgURL: 'https://ibb.co/PW9kzS8' },
    { id: 35, catId: 4, imgURL: 'https://i.ibb.co/S7TF1QY/tractor-black2.png' },
    { id: 36, catId: 4, imgURL: 'https://i.ibb.co/S7TF1QY/tractor-black2.png' },
    { id: 37, catId: 4, imgURL: 'https://i.ibb.co/S7TF1QY/tractor-black2.png' },
    { id: 38, catId: 4, imgURL: 'https://i.ibb.co/S7TF1QY/tractor-black2.png' },
    { id: 39, catId: 4, imgURL: 'https://i.ibb.co/S7TF1QY/tractor-black2.png' },
    { id: 40, catId: 4, imgURL: 'https://i.ibb.co/S7TF1QY/tractor-black2.png' },
    { id: 41, catId: 5, imgURL: 'https://i.postimg.cc/Gt1QtyFN/photo-grid-600-600-2.jpg' },
    { id: 42, catId: 5, imgURL: 'https://i.postimg.cc/Gt1QtyFN/photo-grid-600-600-2.jpg' },
    { id: 43, catId: 5, imgURL: 'https://i.postimg.cc/Gt1QtyFN/photo-grid-600-600-2.jpg' },
    { id: 44, catId: 5, imgURL: 'https://i.postimg.cc/Gt1QtyFN/photo-grid-600-600-2.jpg' },
    { id: 45, catId: 5, imgURL: 'https://i.postimg.cc/Gt1QtyFN/photo-grid-600-600-2.jpg' },
    { id: 46, catId: 5, imgURL: 'https://i.postimg.cc/Gt1QtyFN/photo-grid-600-600-2.jpg' },
    { id: 47, catId: 5, imgURL: 'https://i.postimg.cc/Gt1QtyFN/photo-grid-600-600-2.jpg' },
    { id: 48, catId: 5, imgURL: 'https://i.postimg.cc/Gt1QtyFN/photo-grid-600-600-2.jpg' },
    { id: 49, catId: 5, imgURL: 'https://i.postimg.cc/Gt1QtyFN/photo-grid-600-600-2.jpg' },
    { id: 50, catId: 5, imgURL: 'https://i.postimg.cc/Gt1QtyFN/photo-grid-600-600-2.jpg' },
]